### ISSUE TITLE
Optimize RAM usage

### ISSUE THREAD

**Issue by Shemplo** [Shemplo/Neerc-chat-client#1]
**issue**: on ~1000 it takes over 500 Mb's of RAM
**possible solution**: use ListView instead of scrollable VBox

**Comment by Shemplo** [comment]
Displaying of messages optimized 

But appeared bug with it when the number of messages is small:
ListView сomponent repeats rows from start at the end
![image](https://user-images.githubusercontent.com/14365346/49447023-858dc680-f7e6-11e8-9bd0-8dce35307933.png)

When the number of rows is big enought this bug disappears

**Comment by egormkn** [comment]
Fixed
