### ISSUE TITLE
Tabs in new window

### ISSUE THREAD

**Issue by Shemplo** [Shemplo/Neerc-chat-client#3]
Make possible to open tab in new window
It can be useful when several chats should be followed at once

**Comment by egormkn** [comment]
[![JavaFX: Introducing Detachable Tabs](http://img.youtube.com/vi/ow54mmBgL7w/0.jpg)](http://www.youtube.com/watch?v=ow54mmBgL7w "JavaFX: Introducing Detachable Tabs")
